name: Deploy to dev

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to dev
        run: |
          # Add your deployment commands here
          echo "Deploying to dev environment"