name: Deploy to dev

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build metadata
        uses: actions/download-artifact@v2
        with:
          name: build-metadata

      - name: Echo Docker image tag
        run: |
          IMAGE_TAG=$(cat build-metadata.txt | grep IMAGE_TAG | cut -d '=' -f 2)
          echo "The Docker image tag is: $IMAGE_TAG"